# Name: Hanouf Almogri
## Ex2 - Getting and Knowing your Data
This time we are going to pull data directly from the internet. Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Step 1. Import the necessary libraries

In [1]:
import pandas as pd

Step 2. Import the dataset from this address.


Step 3. Assign it to a variable called chipo.

In [2]:
chipo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep="\t")

Step 4. How many products cost more than $10.00?

In [19]:
(chipo["item_price"] > 10).sum()
# there are 1130 items that cost more than $10.00

np.int64(1130)

Step 5. What is the price of each item?

In [22]:
chipo[["item_name", 'quantity' ,"choice_description", "item_price"]]

,item_name,quantity,choice_description,item_price
0,Chips and Fresh Tomato Salsa,1,NaN,2.39
1,Izze,1,[Clementine],3.39
2,Nantucket Nectar,1,[Apple],3.39
3,Chips and Tomatillo-Green Chili Salsa,1,NaN,2.39
4,Chicken Bowl,2,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...
4617,Steak Burrito,1,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,Steak Burrito,1,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,Chicken Salad Bowl,1,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,Chicken Salad Bowl,1,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,Chicken Salad Bowl,1,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

Step 6. Sort by the name of the item

In [24]:
chipo[["item_name", 'quantity' ,"choice_description", "item_price"]].sort_values("item_name")

,item_name,quantity,choice_description,item_price
3389,6 Pack Soft Drink,2,[Diet Coke],12.98
341,6 Pack Soft Drink,1,[Diet Coke],6.49
1849,6 Pack Soft Drink,1,[Coke],6.49
1860,6 Pack Soft Drink,1,[Diet Coke],6.49
2713,6 Pack Soft Drink,1,[Coke],6.49
...,...,...,...,...
2384,Veggie Soft Tacos,1,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,Veggie Soft Tacos,1,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,Veggie Soft Tacos,1,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,Veggie Soft Tacos,1,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,Veggie Soft Tacos,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

Step 7. What was the quantity of the most expensive item ordered?

In [30]:
chipo.loc[chipo["item_price"].idxmax(), "quantity"]

np.int64(15)

Step 8. What was the quantity of the most expensive item ordered?

In [36]:
chipo.loc[chipo["item_name"] == "Veggie Salad Bowl", "quantity"].sum()

np.int64(18)

Step 9. How many times did someone order more than one Canned Soda?

In [37]:
chipo[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)].shape[0]

20